### ISSUE TITLE
Rendering problem to directory name containing underscore in Windows 10

### ISSUE THREAD

**Issue by GuyBaele** [phylogeography/SpreaD3#24]
Error occurred during a continuous phylogeography spreaD3 analysis. When 'Render to D3' is performed and a name containing an underscore is entered, the following error message appears:

c:\Users\MK\Downloads>java -jar spreaD3_v0.9.6.jar
MRSD is in yyyy/MM/dd format : 2016/7/22
Parsed time line
Parsed the tree
Parsed tree attributes
Parsed map attributes
Created JSON file
Unexpected problem on thread SwingWorker-pool-2-thread-4: C:\Users\MK\Documents\SISMID\continuousPhylogeography\WNT_output4\renderers\d3\d3renderer\index.html (The system cannot find the path specified)
Stack trace:
java.io.FileNotFoundException: C:\Users\MK\Documents\SISMID\continuousPhylogeography\WNT_output4\renderers\d3\d3renderer\index.html (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at renderers.d3.D3Renderer.render(Unknown Source)
        at gui.panels.D3RenderPanel$1.doInBackground(Unknown Source)
        at gui.panels.D3RenderPanel$1.doInBackground(Unknown Source)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by GuyBaele** [comment]
We should also check (what to do with) other special characters, such as spaces, %, &, ...

**Comment by kikiyang** [comment]
The error also occurred in Windows 7 when filename containing an underscore.
